### ISSUE TITLE
Main script crash when creating user. Win 10.

### ISSUE THREAD

**Issue by DuckersMcQuack** [diontimmer/audio-diffusion-gradio#1]
Entered new password, and it crashes.

Enter registration password:
Traceback (most recent call last):
  File "H:\stableaudio\audio-diffusion-gradio-main\gradio_extended.py", line 2179, in <module>
    main(args)
  File "H:\stableaudio\audio-diffusion-gradio-main\gradio_extended.py", line 2062, in main
    interface = stable_audio_interface(
  File "H:\stableaudio\audio-diffusion-gradio-main\gradio_extended.py", line 1897, in create_ui
    theme = gr.Theme.from_hub(theme).set() if theme != "default" else None
  File "H:\stableaudio\audio-diffusion-gradio-main\venv\lib\site-packages\gradio\themes\base.py", line 169, in from_hub
    assets = get_theme_assets(space_info)
  File "H:\stableaudio\audio-diffusion-gradio-main\venv\lib\site-packages\gradio\themes\utils\semver_match.py", line 21, in get_theme_assets
    raise ValueError(f"{space_info.id} is not a valid gradio-theme space!")
ValueError: freddyaboulton/dracula_revamped is not a valid gradio-theme space!
Traceback (most recent call last):
  File "H:\stableaudio\audio-diffusion-gradio-main\launch_script.py", line 207, in <module>
    run(
  File "H:\stableaudio\audio-diffusion-gradio-main\launch_script.py", line 47, in run
    raise RuntimeError(
RuntimeError: MAIN SCRIPT CRASH.
Command: "H:\stableaudio\audio-diffusion-gradio-main\venv\Scripts\python.exe" gradio_extended.py
Error code: 1

**Comment by Gecktendo** [comment]
Having the same issue:

Activating venv and launching.. Run 'gradio_extended.py' directly for use with your own interpreter.
Launching using Python: C:\GitPrograms\audio-diffusion-gradio\venv\Scripts\python.exe
Starting launch script...
Checking pip upgrade..
Installing Upgrading pip
Requirement already satisfied: pip in c:\gitprograms\audio-diffusion-gradio\venv\lib\site-packages (24.0)
Version of xformers: 0.0.26.post1
Version of stable_audio_tools: 0.0.15
Version of gradio: 3.48.0
Launch success! Starting main script, this might take a bit..
Traceback (most recent call last):
  File "C:\GitPrograms\audio-diffusion-gradio\gradio_extended.py", line 18, in <module>
    from stable_audio_tools.data.dataset import create_dataloader_from_configs_and_args
ImportError: cannot import name 'create_dataloader_from_configs_and_args' from 'stable_audio_tools.data.dataset' (C:\GitPrograms\audio-diffusion-gradio\venv\lib\site-packages\stable_audio_tools\data\dataset.py)
Traceback (most recent call last):
  File "C:\GitPrograms\audio-diffusion-gradio\launch_script.py", line 207, in <module>
    run(
  File "C:\GitPrograms\audio-diffusion-gradio\launch_script.py", line 47, in run
    raise RuntimeError(
RuntimeError: MAIN SCRIPT CRASH.
Command: "C:\GitPrograms\audio-diffusion-gradio\venv\Scripts\python.exe" gradio_extended.py
Error code: 1
Press any key to continue . . .

I noticed that "(C:\GitPrograms\audio-diffusion-gradio\venv\lib\site-packages\stable_audio_tools\data\dataset.py" is being called when in the newest version they use "Lib". I'm assuming the path change broke the script?

**Comment by diontimmer** [comment]
Apologies! Will update the project to the latest version of the library when i am back from touring

**Comment by Gecktendo** [comment]
No pressure to get this done quickly or anything like that, I was just wanting to get some stuff ready for training, that's all. Enjoy the tour!

**Comment by diontimmer** [comment]
should be fixed now :)
