### ISSUE TITLE
init audio issue 

### ISSUE THREAD

**Issue by 3blackbar** [diontimmer/audio-diffusion-gradio#4]
I gave it wav sample 

`Generating using float16 precision.
Converting init audio to fp16
310717212
Input type (torch.cuda.HalfTensor) and weight type (torch.cuda.FloatTensor) should be the same
Traceback (most recent call last):
  File "D:\saudio\gradio_extended.py", line 582, in generate
    latents = generate_diffusion_cond(
  File "D:\saudio\venv\lib\site-packages\stable_audio_tools\inference\generation.py", line 175, in generate_diffusion_cond
    init_audio = prepare_audio(init_audio, in_sr=in_sr, target_sr=model.sample_rate, target_length=audio_sample_size, target_channels=io_channels, device=device)
  File "D:\saudio\venv\lib\site-packages\stable_audio_tools\inference\utils.py", line 23, in prepare_audio
    audio = resample_tf(audio)
  File "D:\saudio\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\saudio\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\saudio\venv\lib\site-packages\torchaudio\transforms\_transforms.py", line 979, in forward
    return _apply_sinc_resample_kernel(waveform, self.orig_freq, self.new_freq, self.gcd, self.kernel, self.width)
  File "D:\saudio\venv\lib\site-packages\torchaudio\functional\functional.py", line 1466, in _apply_sinc_resample_kernel
    resampled = torch.nn.functional.conv1d(waveform[:, None], kernel, stride=orig_freq)
RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.cuda.FloatTensor) should be the same

`

**Comment by 3blackbar** [comment]
yup it has to be converted , i went without fp16 and it works
